name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"

