name: Test
on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  test-docker-build-check:
    name: test-docker-build-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
