name: Test
on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  test-root-dir:
    name: test-docker-build-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}

  test-specific-workdir:
    name: test-docker-build-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          workdir: testdata
          filter_mode: nofilter
